#!/bin/bash

set -e  # Exit immediately if a command fails

# Update and install packages
echo "[+] Updating and installing packages..."
sudo apt update
sudo apt install -y tmux neovim eza zoxide zsh neofetch alacritty kitty gcc g++ vim git curl

# Clone your GitHub repos
echo "[+] Cloning your GitHub repositories..."
mkdir -p ~/projects
cd ~/projects
git clone https://github.com/69iqqq/windows.git
git clone https://github.com/69iqqq/hello.git

# Set up NvChad and OwnVim configs
echo "[+] Setting up NvChad and OwnVim configs..."
mkdir -p ~/.config
cp -r ~/projects/windows/NvChad ~/.config/
cp -r ~/projects/windows/OwnVim2 ~/.config/OwnVim

# Install oh-my-zsh
echo "[+] Installing oh-my-zsh..."
export RUNZSH=no  # Prevent auto-switching to zsh after install
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# Install zsh plugins
echo "[+] Installing zsh plugins..."
ZSH_CUSTOM=${ZSH_CUSTOM:-~/.oh-my-zsh/custom}
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git "$ZSH_CUSTOM/plugins/zsh-syntax-highlighting"
git clone https://github.com/zsh-users/zsh-autosuggestions "$ZSH_CUSTOM/plugins/zsh-autosuggestions"

# Reminder to change default shell to zsh
echo "[+] Done! Don't forget to run: chsh -s $(which zsh)"
